### ISSUE TITLE
srrg2_proslam vs srrg_proslam speed

### ISSUE THREAD

**Issue by zbynekwinkler** [srrg-sapienza/srrg2_proslam#2]
I see big difference in speed comparing `srrg2_proslam` and `srrg_proslam` - 40fps vs 60fps. Is that expected? Both were compiled without `-march=native`.

**Comment by istinj** [comment]
Hello!
Yes this is expected. The first version of `srrg_proslam` was designed in a end-to-end fashion and, hence, the implementation was overfitted to the VO problem. In this case, instead, the huge gain in flexibility requires is paid with a code overhead, which impacts on the fps (still above real-time).
